### ISSUE TITLE
Post Removal Reqeust - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [countofkrakow/Miscellaneous-puzzle-code#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. The folders in this repository contains solution code to our homework assignments. Specifically:

Anagrams
Evil Hangman
Rocket Ship

These posts' solution codes are indexed by Google, enabling current students to easily find them and cheat on their assignments.

Would you please remove your HW repositories or make it private in order to help us enforce our academic policy?

By removing these repositories, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu

More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by countofkrakow** [comment]
Sorry about that.  I've removed the three folders.  Have any students used my work to cheat?
